Imports System
Imports DataDynamics.ActiveReports
Imports DataDynamics.ActiveReports.Document

Public Class ActiveReport2
    Inherits ActiveReport
    Public Sub New()
        MyBase.New()
        InitializeReport()
    End Sub
#Region "ActiveReports Designer generated code"
    Private WithEvents ReportHeader As ReportHeader = Nothing
    Private WithEvents PageHeader As PageHeader = Nothing
    Private WithEvents GrpHdrWorkCondition As GroupHeader = Nothing
    Private WithEvents GrpHdrDatafile As GroupHeader = Nothing
    Private WithEvents GrpHdrDatafileTable As GroupHeader = Nothing
    Private WithEvents GrpHdrStadGraph As GroupHeader = Nothing
    Private WithEvents GrpHdrSpectrum As GroupHeader = Nothing
    Private WithEvents GrpHdrPeakValley As GroupHeader = Nothing
    Private WithEvents GrpHdrRepeatResults As GroupHeader = Nothing
    Private WithEvents Detail As Detail = Nothing
    Private WithEvents GroupFooter8 As GroupFooter = Nothing
    Private WithEvents GroupFooter6 As GroupFooter = Nothing
    Private WithEvents GroupFooter5 As GroupFooter = Nothing
    Private WithEvents GroupFooter4 As GroupFooter = Nothing
    Private WithEvents GroupFooter3 As GroupFooter = Nothing
    Private WithEvents GroupFooter2 As GroupFooter = Nothing
    Private WithEvents GroupFooter1 As GroupFooter = Nothing
    Private WithEvents PageFooter As PageFooter = Nothing
    Private WithEvents ReportFooter As ReportFooter = Nothing
	Private pictLogo As Picture = Nothing
	Private lblReportHeader As Label = Nothing
	Private lblReportHeader2 As Label = Nothing
	Private lblReportHeader3 As Label = Nothing
	Private lblReportHeader4 As Label = Nothing
	Private ReportHeaderLine As Line = Nothing
	Private lblPageHeader As Label = Nothing
	Private lblWavelengrh As Label = Nothing
	Private lblSpectalBandpass As Label = Nothing
	Private lblWorkingRange As Label = Nothing
	Private TxtLable1 As Label = Nothing
	Private Txt1 As Label = Nothing
	Private TxtLable2 As Label = Nothing
	Private Txt2 As Label = Nothing
	Private lblHeader As Label = Nothing
	Private Tablelbl1 As Label = Nothing
	Private Tablelbl2 As Label = Nothing
	Private Tablelbl3 As Label = Nothing
	Private Tablelbl4 As Label = Nothing
	Private Tablelbl5 As Label = Nothing
	Private Tablelbl6 As Label = Nothing
	Private Tablelbl7 As Label = Nothing
	Private Label5 As Label = Nothing
	Private StadGraphLbl1 As Label = Nothing
	Private StadGraphLbl2 As Label = Nothing
	Private StadGraphLbl3 As Label = Nothing
	Private StadGraphLbl4 As Label = Nothing
	Private Label6 As Label = Nothing
	Private lblHdrSpectrum As Label = Nothing
	Private lblCol1 As Label = Nothing
	Private lblCol2 As Label = Nothing
	Private lblCol3 As Label = Nothing
	Private lblCol4 As Label = Nothing
	Private lblHdrSpectrum1 As Label = Nothing
	Private lblHdrSpectrum2 As Label = Nothing
	Private lblSerNo1 As Label = Nothing
	Private LblWv1 As Label = Nothing
	Private lblPeak1 As Label = Nothing
	Private lblSerNo2 As Label = Nothing
	Private LblWv2 As Label = Nothing
	Private lblValley1 As Label = Nothing
	Private lblHdrPeakValley1 As Label = Nothing
	Private TxtStdSamp As Label = Nothing
	Private StdSampName As Label = Nothing
	Private TxtStdSampName As Label = Nothing
	Private Abso As Label = Nothing
	Private TxtAbso As Label = Nothing
	Private Conc As Label = Nothing
	Private TxtConc As Label = Nothing
	Private lblDtlInfo As Label = Nothing
	Private TxtDtlInfo As Label = Nothing
	Private FlameShape As Shape = Nothing
	Private lblHeader1 As Label = Nothing
	Private lblElement As Label = Nothing
	Private lblAtWt As Label = Nothing
	Private lblHeader2 As Label = Nothing
	Private Label1 As Label = Nothing
	Private lblHeader3 As Label = Nothing
	Private Label3 As Label = Nothing
	Private lblHeader4 As Label = Nothing
	Private lblHeader5 As Label = Nothing
	Private lblLampCurr As Label = Nothing
	Private lblSupport As Label = Nothing
	Private lblFuel As Label = Nothing
	Private lblFlameSto As Label = Nothing
	Private lblLampCurrVal As Label = Nothing
	Private lblSupportVal As Label = Nothing
	Private lblFuelVal As Label = Nothing
	Private lblFlameStoVal As Label = Nothing
	Private lblHeader6 As Label = Nothing
	Private Label4 As Label = Nothing
	Private lblWorking As Label = Nothing
	Private lblWorking1 As Label = Nothing
	Private lblWavelength As Label = Nothing
	Private lblSpectral As Label = Nothing
	Private lblOptimumWorkingRange As Label = Nothing
	Private lblFlame As Label = Nothing
	Private lblWavelength1 As Label = Nothing
	Private lblNote As Label = Nothing
	Private lblNoteVal As Label = Nothing
	Private lblWavelength1Val As Label = Nothing
	Private lblBandwidth As Label = Nothing
	Private lblBandwidthVal As Label = Nothing
	Private lblFuel1 As Label = Nothing
	Private lblFuel1Val As Label = Nothing
	Private lblSupport1 As Label = Nothing
	Private lblSupport1Val As Label = Nothing
	Private lblNote1 As Label = Nothing
	Private lblNote1Val As Label = Nothing
	Private lblPageFooter As Label = Nothing
	Private lblPageNo As Label = Nothing
	Private PageFooterLine As Line = Nothing
	Private lblReportFooter As Label = Nothing
	Private ReportFooterLine As Line = Nothing
	Public Sub InitializeReport()
		Me.LoadLayout(Me.GetType, "AAS203.ActiveReport2.rpx")
		Me.ReportHeader = CType(Me.Sections("ReportHeader"),DataDynamics.ActiveReports.ReportHeader)
		Me.PageHeader = CType(Me.Sections("PageHeader"),DataDynamics.ActiveReports.PageHeader)
		Me.GrpHdrWorkCondition = CType(Me.Sections("GrpHdrWorkCondition"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrDatafile = CType(Me.Sections("GrpHdrDatafile"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrDatafileTable = CType(Me.Sections("GrpHdrDatafileTable"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrStadGraph = CType(Me.Sections("GrpHdrStadGraph"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrSpectrum = CType(Me.Sections("GrpHdrSpectrum"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrPeakValley = CType(Me.Sections("GrpHdrPeakValley"),DataDynamics.ActiveReports.GroupHeader)
		Me.GrpHdrRepeatResults = CType(Me.Sections("GrpHdrRepeatResults"),DataDynamics.ActiveReports.GroupHeader)
		Me.Detail = CType(Me.Sections("Detail"),DataDynamics.ActiveReports.Detail)
		Me.GroupFooter8 = CType(Me.Sections("GroupFooter8"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter6 = CType(Me.Sections("GroupFooter6"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter5 = CType(Me.Sections("GroupFooter5"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter4 = CType(Me.Sections("GroupFooter4"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter3 = CType(Me.Sections("GroupFooter3"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter2 = CType(Me.Sections("GroupFooter2"),DataDynamics.ActiveReports.GroupFooter)
		Me.GroupFooter1 = CType(Me.Sections("GroupFooter1"),DataDynamics.ActiveReports.GroupFooter)
		Me.PageFooter = CType(Me.Sections("PageFooter"),DataDynamics.ActiveReports.PageFooter)
		Me.ReportFooter = CType(Me.Sections("ReportFooter"),DataDynamics.ActiveReports.ReportFooter)
		Me.pictLogo = CType(Me.ReportHeader.Controls(0),DataDynamics.ActiveReports.Picture)
		Me.lblReportHeader = CType(Me.ReportHeader.Controls(1),DataDynamics.ActiveReports.Label)
		Me.lblReportHeader2 = CType(Me.ReportHeader.Controls(2),DataDynamics.ActiveReports.Label)
		Me.lblReportHeader3 = CType(Me.ReportHeader.Controls(3),DataDynamics.ActiveReports.Label)
		Me.lblReportHeader4 = CType(Me.ReportHeader.Controls(4),DataDynamics.ActiveReports.Label)
		Me.ReportHeaderLine = CType(Me.ReportHeader.Controls(5),DataDynamics.ActiveReports.Line)
		Me.lblPageHeader = CType(Me.PageHeader.Controls(0),DataDynamics.ActiveReports.Label)
		Me.lblWavelengrh = CType(Me.GrpHdrWorkCondition.Controls(0),DataDynamics.ActiveReports.Label)
		Me.lblSpectalBandpass = CType(Me.GrpHdrWorkCondition.Controls(1),DataDynamics.ActiveReports.Label)
		Me.lblWorkingRange = CType(Me.GrpHdrWorkCondition.Controls(2),DataDynamics.ActiveReports.Label)
		Me.TxtLable1 = CType(Me.GrpHdrDatafile.Controls(0),DataDynamics.ActiveReports.Label)
		Me.Txt1 = CType(Me.GrpHdrDatafile.Controls(1),DataDynamics.ActiveReports.Label)
		Me.TxtLable2 = CType(Me.GrpHdrDatafile.Controls(2),DataDynamics.ActiveReports.Label)
		Me.Txt2 = CType(Me.GrpHdrDatafile.Controls(3),DataDynamics.ActiveReports.Label)
		Me.lblHeader = CType(Me.GrpHdrDatafile.Controls(4),DataDynamics.ActiveReports.Label)
		Me.Tablelbl1 = CType(Me.GrpHdrDatafileTable.Controls(0),DataDynamics.ActiveReports.Label)
		Me.Tablelbl2 = CType(Me.GrpHdrDatafileTable.Controls(1),DataDynamics.ActiveReports.Label)
		Me.Tablelbl3 = CType(Me.GrpHdrDatafileTable.Controls(2),DataDynamics.ActiveReports.Label)
		Me.Tablelbl4 = CType(Me.GrpHdrDatafileTable.Controls(3),DataDynamics.ActiveReports.Label)
		Me.Tablelbl5 = CType(Me.GrpHdrDatafileTable.Controls(4),DataDynamics.ActiveReports.Label)
		Me.Tablelbl6 = CType(Me.GrpHdrDatafileTable.Controls(5),DataDynamics.ActiveReports.Label)
		Me.Tablelbl7 = CType(Me.GrpHdrDatafileTable.Controls(6),DataDynamics.ActiveReports.Label)
		Me.Label5 = CType(Me.GrpHdrDatafileTable.Controls(7),DataDynamics.ActiveReports.Label)
		Me.StadGraphLbl1 = CType(Me.GrpHdrStadGraph.Controls(0),DataDynamics.ActiveReports.Label)
		Me.StadGraphLbl2 = CType(Me.GrpHdrStadGraph.Controls(1),DataDynamics.ActiveReports.Label)
		Me.StadGraphLbl3 = CType(Me.GrpHdrStadGraph.Controls(2),DataDynamics.ActiveReports.Label)
		Me.StadGraphLbl4 = CType(Me.GrpHdrStadGraph.Controls(3),DataDynamics.ActiveReports.Label)
		Me.Label6 = CType(Me.GrpHdrStadGraph.Controls(4),DataDynamics.ActiveReports.Label)
		Me.lblHdrSpectrum = CType(Me.GrpHdrSpectrum.Controls(0),DataDynamics.ActiveReports.Label)
		Me.lblCol1 = CType(Me.GrpHdrSpectrum.Controls(1),DataDynamics.ActiveReports.Label)
		Me.lblCol2 = CType(Me.GrpHdrSpectrum.Controls(2),DataDynamics.ActiveReports.Label)
		Me.lblCol3 = CType(Me.GrpHdrSpectrum.Controls(3),DataDynamics.ActiveReports.Label)
		Me.lblCol4 = CType(Me.GrpHdrSpectrum.Controls(4),DataDynamics.ActiveReports.Label)
		Me.lblHdrSpectrum1 = CType(Me.GrpHdrSpectrum.Controls(5),DataDynamics.ActiveReports.Label)
		Me.lblHdrSpectrum2 = CType(Me.GrpHdrSpectrum.Controls(6),DataDynamics.ActiveReports.Label)
		Me.lblSerNo1 = CType(Me.GrpHdrPeakValley.Controls(0),DataDynamics.ActiveReports.Label)
		Me.LblWv1 = CType(Me.GrpHdrPeakValley.Controls(1),DataDynamics.ActiveReports.Label)
		Me.lblPeak1 = CType(Me.GrpHdrPeakValley.Controls(2),DataDynamics.ActiveReports.Label)
		Me.lblSerNo2 = CType(Me.GrpHdrPeakValley.Controls(3),DataDynamics.ActiveReports.Label)
		Me.LblWv2 = CType(Me.GrpHdrPeakValley.Controls(4),DataDynamics.ActiveReports.Label)
		Me.lblValley1 = CType(Me.GrpHdrPeakValley.Controls(5),DataDynamics.ActiveReports.Label)
		Me.lblHdrPeakValley1 = CType(Me.GrpHdrPeakValley.Controls(6),DataDynamics.ActiveReports.Label)
		Me.TxtStdSamp = CType(Me.GrpHdrRepeatResults.Controls(0),DataDynamics.ActiveReports.Label)
		Me.StdSampName = CType(Me.GrpHdrRepeatResults.Controls(1),DataDynamics.ActiveReports.Label)
		Me.TxtStdSampName = CType(Me.GrpHdrRepeatResults.Controls(2),DataDynamics.ActiveReports.Label)
		Me.Abso = CType(Me.GrpHdrRepeatResults.Controls(3),DataDynamics.ActiveReports.Label)
		Me.TxtAbso = CType(Me.GrpHdrRepeatResults.Controls(4),DataDynamics.ActiveReports.Label)
		Me.Conc = CType(Me.GrpHdrRepeatResults.Controls(5),DataDynamics.ActiveReports.Label)
		Me.TxtConc = CType(Me.GrpHdrRepeatResults.Controls(6),DataDynamics.ActiveReports.Label)
		Me.lblDtlInfo = CType(Me.GrpHdrRepeatResults.Controls(7),DataDynamics.ActiveReports.Label)
		Me.TxtDtlInfo = CType(Me.GrpHdrRepeatResults.Controls(8),DataDynamics.ActiveReports.Label)
		Me.FlameShape = CType(Me.Detail.Controls(0),DataDynamics.ActiveReports.Shape)
		Me.lblHeader1 = CType(Me.Detail.Controls(1),DataDynamics.ActiveReports.Label)
		Me.lblElement = CType(Me.Detail.Controls(2),DataDynamics.ActiveReports.Label)
		Me.lblAtWt = CType(Me.Detail.Controls(3),DataDynamics.ActiveReports.Label)
		Me.lblHeader2 = CType(Me.Detail.Controls(4),DataDynamics.ActiveReports.Label)
		Me.Label1 = CType(Me.Detail.Controls(5),DataDynamics.ActiveReports.Label)
		Me.lblHeader3 = CType(Me.Detail.Controls(6),DataDynamics.ActiveReports.Label)
		Me.Label3 = CType(Me.Detail.Controls(7),DataDynamics.ActiveReports.Label)
		Me.lblHeader4 = CType(Me.Detail.Controls(8),DataDynamics.ActiveReports.Label)
		Me.lblHeader5 = CType(Me.Detail.Controls(9),DataDynamics.ActiveReports.Label)
		Me.lblLampCurr = CType(Me.Detail.Controls(10),DataDynamics.ActiveReports.Label)
		Me.lblSupport = CType(Me.Detail.Controls(11),DataDynamics.ActiveReports.Label)
		Me.lblFuel = CType(Me.Detail.Controls(12),DataDynamics.ActiveReports.Label)
		Me.lblFlameSto = CType(Me.Detail.Controls(13),DataDynamics.ActiveReports.Label)
		Me.lblLampCurrVal = CType(Me.Detail.Controls(14),DataDynamics.ActiveReports.Label)
		Me.lblSupportVal = CType(Me.Detail.Controls(15),DataDynamics.ActiveReports.Label)
		Me.lblFuelVal = CType(Me.Detail.Controls(16),DataDynamics.ActiveReports.Label)
		Me.lblFlameStoVal = CType(Me.Detail.Controls(17),DataDynamics.ActiveReports.Label)
		Me.lblHeader6 = CType(Me.Detail.Controls(18),DataDynamics.ActiveReports.Label)
		Me.Label4 = CType(Me.Detail.Controls(19),DataDynamics.ActiveReports.Label)
		Me.lblWorking = CType(Me.Detail.Controls(20),DataDynamics.ActiveReports.Label)
		Me.lblWorking1 = CType(Me.Detail.Controls(21),DataDynamics.ActiveReports.Label)
		Me.lblWavelength = CType(Me.Detail.Controls(22),DataDynamics.ActiveReports.Label)
		Me.lblSpectral = CType(Me.Detail.Controls(23),DataDynamics.ActiveReports.Label)
		Me.lblOptimumWorkingRange = CType(Me.Detail.Controls(24),DataDynamics.ActiveReports.Label)
		Me.lblFlame = CType(Me.Detail.Controls(25),DataDynamics.ActiveReports.Label)
		Me.lblWavelength1 = CType(Me.Detail.Controls(26),DataDynamics.ActiveReports.Label)
		Me.lblNote = CType(Me.Detail.Controls(27),DataDynamics.ActiveReports.Label)
		Me.lblNoteVal = CType(Me.Detail.Controls(28),DataDynamics.ActiveReports.Label)
		Me.lblWavelength1Val = CType(Me.Detail.Controls(29),DataDynamics.ActiveReports.Label)
		Me.lblBandwidth = CType(Me.Detail.Controls(30),DataDynamics.ActiveReports.Label)
		Me.lblBandwidthVal = CType(Me.Detail.Controls(31),DataDynamics.ActiveReports.Label)
		Me.lblFuel1 = CType(Me.Detail.Controls(32),DataDynamics.ActiveReports.Label)
		Me.lblFuel1Val = CType(Me.Detail.Controls(33),DataDynamics.ActiveReports.Label)
		Me.lblSupport1 = CType(Me.Detail.Controls(34),DataDynamics.ActiveReports.Label)
		Me.lblSupport1Val = CType(Me.Detail.Controls(35),DataDynamics.ActiveReports.Label)
		Me.lblNote1 = CType(Me.Detail.Controls(36),DataDynamics.ActiveReports.Label)
		Me.lblNote1Val = CType(Me.Detail.Controls(37),DataDynamics.ActiveReports.Label)
		Me.lblPageFooter = CType(Me.PageFooter.Controls(0),DataDynamics.ActiveReports.Label)
		Me.lblPageNo = CType(Me.PageFooter.Controls(1),DataDynamics.ActiveReports.Label)
		Me.PageFooterLine = CType(Me.PageFooter.Controls(2),DataDynamics.ActiveReports.Line)
		Me.lblReportFooter = CType(Me.ReportFooter.Controls(0),DataDynamics.ActiveReports.Label)
		Me.ReportFooterLine = CType(Me.ReportFooter.Controls(1),DataDynamics.ActiveReports.Line)
	End Sub

#End Region
End Class
