//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


 // ERROR: Not supported in C#: OptionDeclaration
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.ReportSource;
using CrystalDecisions.Shared;
using System;
using System.ComponentModel;


public class crptAllReport : ReportClass
{

	public crptAllReport()
	{
		base.New();
	}

	public override string ResourceName {
		get { return "crptAllReport.rpt"; }
			//Do nothing
		set { }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section1 {
		get { return this.ReportDefinition.Sections(0); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section2 {
		get { return this.ReportDefinition.Sections(1); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section6 {
		get { return this.ReportDefinition.Sections(2); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section7 {
		get { return this.ReportDefinition.Sections(3); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section51 {
		get { return this.ReportDefinition.Sections(4); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section3 {
		get { return this.ReportDefinition.Sections(5); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section28 {
		get { return this.ReportDefinition.Sections(6); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section8 {
		get { return this.ReportDefinition.Sections(7); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section9 {
		get { return this.ReportDefinition.Sections(8); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section31 {
		get { return this.ReportDefinition.Sections(9); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section10 {
		get { return this.ReportDefinition.Sections(10); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section11 {
		get { return this.ReportDefinition.Sections(11); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section32 {
		get { return this.ReportDefinition.Sections(12); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section12 {
		get { return this.ReportDefinition.Sections(13); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section13 {
		get { return this.ReportDefinition.Sections(14); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section33 {
		get { return this.ReportDefinition.Sections(15); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section14 {
		get { return this.ReportDefinition.Sections(16); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section34 {
		get { return this.ReportDefinition.Sections(17); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section35 {
		get { return this.ReportDefinition.Sections(18); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section36 {
		get { return this.ReportDefinition.Sections(19); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section15 {
		get { return this.ReportDefinition.Sections(20); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section37 {
		get { return this.ReportDefinition.Sections(21); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section29 {
		get { return this.ReportDefinition.Sections(22); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section16 {
		get { return this.ReportDefinition.Sections(23); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section40 {
		get { return this.ReportDefinition.Sections(24); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section27 {
		get { return this.ReportDefinition.Sections(25); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section17 {
		get { return this.ReportDefinition.Sections(26); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section39 {
		get { return this.ReportDefinition.Sections(27); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section18 {
		get { return this.ReportDefinition.Sections(28); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section19 {
		get { return this.ReportDefinition.Sections(29); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section23 {
		get { return this.ReportDefinition.Sections(30); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section24 {
		get { return this.ReportDefinition.Sections(31); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section25 {
		get { return this.ReportDefinition.Sections(32); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section26 {
		get { return this.ReportDefinition.Sections(33); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section22 {
		get { return this.ReportDefinition.Sections(34); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section20 {
		get { return this.ReportDefinition.Sections(35); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section21 {
		get { return this.ReportDefinition.Sections(36); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section48 {
		get { return this.ReportDefinition.Sections(37); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section4 {
		get { return this.ReportDefinition.Sections(38); }
	}

	[Browsable(false), DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
	public CrystalDecisions.CrystalReports.Engine.Section Section5 {
		get { return this.ReportDefinition.Sections(39); }
	}
}

[System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
public class CachedcrptAllReport : Component, ICachedReport
{

	public CachedcrptAllReport()
	{
		base.New();
	}

	public virtual bool CrystalDecisions.ReportSource.ICachedReport.IsCacheable {
		get { return true; }
			//
		set { }
	}

	public virtual bool CrystalDecisions.ReportSource.ICachedReport.ShareDBLogonInfo {
		get { return false; }
			//
		set { }
	}

	public virtual System.TimeSpan CrystalDecisions.ReportSource.ICachedReport.CacheTimeOut {
		get { return CachedReportConstants.DEFAULT_TIMEOUT; }
			//
		set { }
	}

	public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CrystalDecisions.ReportSource.ICachedReport.CreateReport()
	{
		crptAllReport rpt = new crptAllReport();
		rpt.Site = this.Site;
		return rpt;
	}

	public virtual string CrystalDecisions.ReportSource.ICachedReport.GetCustomizedCacheKey(RequestContext request)
	{
		String key = null;
		//// The following is the code used to generate the default
		//// cache key for caching report jobs in the ASP.NET Cache.
		//// Feel free to modify this code to suit your needs.
		//// Returning key == null causes the default cache key to
		//// be generated.
		//
		//key = RequestContext.BuildCompleteCacheKey(
		//    request,
		//    null,       // sReportFilename
		//    this.GetType(),
		//    this.ShareDBLogonInfo );
		return key;
	}
}
